default:
  infra: 
    nomad:
      auto_revert: true 
      role: "public-cluster"
      aws_lifecycle: "spot"
      resources:
        cpu: 500
        memory: 500
    docker:
      remote_repo: "315316724794.dkr.ecr.us-east-1.amazonaws.com/"
    apache:
      access_log: "/alloc/logs/app.access.log"
      error_log: "/alloc/logs/app.error.log"
    remote_syslog:
      exclude_patterns: "['/server-status/?auto', '\"-\" 408 - \"-\" \"-\"']"

prod: 
  infra: 
    nomad:  
      auto_revert: true
      aws_lifecycle: "scheduled"
