default:
  infra:
    apache:
      access_log: "/alloc/logs/static-assets.access.log"
      error_log: "/alloc/logs/static-assets.error.log"
    remote_syslog:
      exclude_patterns: "['/server-status/?auto', '\"-\" 408 - \"-\" \"-\"']"
